### ISSUE TITLE
When animated, some sliders get stuck at the end

### ISSUE THREAD

**Issue by ChristopherChudzicki** [ChristopherChudzicki/math3d#52]
I'm not sure if this is browser dependent. It's definitely dependent on slider animation speed.

It happens in Safari 10.0.3 for me with a slider [0, 2pi] animated at 2x speed.

**Comment by stardust66** [comment]
Are there other cases found for this issue? The [function](https://github.com/ChristopherChudzicki/math3d/blob/master/resources/math3d_app.js#L283-L289) passed to setInterval seems to keep running but the condition [here](https://github.com/ChristopherChudzicki/math3d/blob/master/resources/math3d_app.js#L285-L287) never evaluates to `true`. I don't know exactly why but I suspect that it has something to do with the precision of the numbers, since it happens for pi and that has a lot of decimals. Using a less complex representation of the step variable seems to fix the issue for the [0, 2pi] at 2x speed case:
```
ele.step = Math.fround(ele.step);
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/fround

**Comment by ChristopherChudzicki** [comment]
I think that makes sense. I don't think I've seen instances of this bug involving numbers with only a few digits, and I couldn't find any such instances tonight.

And you're right, that does fix it.
